In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

b = 785.1811367994083
w = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [3]:
print(X_train.shape)

(3, 4)


In [4]:
print(X_train.shape[0])
print(X_train.shape[1])

3
4


In [5]:
print(X_train)
print(w)
print(X_train[0])

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[  0.39133535  18.75376741 -53.36032453 -26.42131618]
[2104    5    1   45]


In [6]:
f_wb_i = np.dot(X_train[0], w) + b
print(f_wb_i)

459.99999761940825


In [7]:
print(X_train[0,:])

[2104    5    1   45]


In [8]:
dj_dw = np.zeros((4,))
dj_dw = X_train
print(dj_dw)

dj_dw1 = np.zeros(4)
print(dj_dw1)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[0. 0. 0. 0.]


In [18]:
m = np.arange(10).reshape(-1,5)

In [19]:
print(m)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
p,q = X_train.shape

In [12]:
print(p)

3


In [13]:
print(q)

4


In [14]:
print(X_train[1,2])

2


In [15]:
def compute_gradient(x,y,w,b):
    m,n = x.shape
    dj_dw = np.zeros(n)
    dj_db = 0
    
    for i in range(m):
        error = (np.dot(x[i],w) + b) - y[i]
        
        for j in range(n):
            dj_dw[j] += error*x[i,j]
        
        dj_db += error
    
    dj_dw /= m
    dj_db /= n

    return dj_dw,dj_db
        

In [16]:
dj_dw_int,dj_db_int = compute_gradient(X_train,y_train,w,b)
print(dj_dw_int)
print(dj_db_int)

[-2.72623581e-03 -6.27197272e-06 -2.21745580e-06 -6.92403399e-05]
-1.2554438768574983e-06


In [17]:
def gradient_discent(x,y,w_in,b_in,gradient_function,alpha,num_iters):

    w = copy.deepcopy(w_in)
    b = b_in
    
    for i in range(num_iters):
        dj_dw,dj_db = gradient_function(x,y,w,b)
        
        w -= alpha*dj_dw
        b -= alpha*dj_db